### ISSUE TITLE
separate bootstrap.scss from core.scss

### ISSUE THREAD

**Issue by kmergen** [coreui/coreui-free-bootstrap-admin-template#345] opened 2018-02-09 21:31 UTC
It were helpfull, if you can separate bootstrap.scss from core.scss, because I write all my sass files in one big file and then create sourcemaps for all included files.
It is important for my projects that I can see what is pure bootstrap style and what is a coreui style.

**Comment by pelted** [comment] 2018-02-16 21:10
duplicate of #310

**Closed** 2018-06-03 13:43 UTC
