### ISSUE TITLE
User menu hides in mobile view!!

### ISSUE THREAD

**Issue by amint** [coreui/coreui-free-bootstrap-admin-template#199] opened 2017-07-10 02:41 UTC
The top-right user menu hides in narrow screens (smartphone, or tablet view)

![image](https://user-images.githubusercontent.com/8526622/28001048-8438312c-64de-11e7-8386-ead0b9dbc0fd.png)

**Comment by amint** [comment] 2017-07-18 17:23
@theill @ognjenm @tyaakow @borisdamevin @felipear89 
Sorry guys but did not know who to ping for this issue,

**Comment by mrholek** [comment] 2017-07-19 06:33
Can you share your header code?

**Comment by amint** [comment] 2017-07-21 04:38
Its visible at your demo too. You can use the header code of this demo:
http://coreui.io/demo/Ajax_Demo/#main.html

**Comment by mrholek** [comment] 2017-07-21 07:29
Please change your header code to this
```html
<header class="app-header navbar">
  <button class="navbar-toggler mobile-sidebar-toggler d-lg-none" type="button">&#9776;</button>
    <a class="navbar-brand" href="#"></a>
    <ul class="nav navbar-nav d-md-down-none">
      <li class="nav-item">
        <a class="nav-link navbar-toggler sidebar-toggler" href="#">&#9776;</a>
      </li>
      <li class="nav-item px-3">
        <a class="nav-link" href="#">Dashboard</a>
      </li>
      <li class="nav-item px-3">
        <a class="nav-link" href="#">Users</a>
      </li>
      <li class="nav-item px-3">
        <a class="nav-link" href="#">Settings</a>
      </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item d-md-down-none">
        <a class="nav-link" href="#"><i class="icon-bell"></i><span class="badge badge-pill badge-danger">5</span></a>
      </li>
      <li class="nav-item d-md-down-none">
        <a class="nav-link" href="#"><i class="icon-list"></i></a>
      </li>
      <li class="nav-item d-md-down-none">
        <a class="nav-link" href="#"><i class="icon-location-pin"></i></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          <img src="img/avatars/6.jpg" class="img-avatar" alt="admin@bootstrapmaster.com">
          <span class="d-md-down-none">admin</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-header text-center"><strong>Account</strong></div>
          <a class="dropdown-item" href="#"><i class="fa fa-bell-o"></i> Updates<span class="badge badge-info">42</span></a>
          <a class="dropdown-item" href="#"><i class="fa fa-envelope-o"></i> Messages<span class="badge badge-success">42</span></a>
          <a class="dropdown-item" href="#"><i class="fa fa-tasks"></i> Tasks<span class="badge badge-danger">42</span></a>
          <a class="dropdown-item" href="#"><i class="fa fa-comments"></i> Comments<span class="badge badge-warning">42</span></a>
          <div class="dropdown-header text-center"><strong>Settings</strong></div>
          <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profile</a>
          <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i> Settings</a>
          <a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="badge badge-default">42</span></a>
          <a class="dropdown-item" href="#"><i class="fa fa-file"></i> Projects<span class="badge badge-primary">42</span></a>
          <div class="divider"></div>
          <a class="dropdown-item" href="#"><i class="fa fa-shield"></i> Lock Account</a>
          <a class="dropdown-item" href="#"><i class="fa fa-lock"></i> Logout</a>
        </div>
      </li>
      <li class="nav-item d-md-down-none">
        <a class="nav-link navbar-toggler aside-menu-toggler" href="#">&#9776;</a>
      </li>
    </ul>
  </header>
```

**Comment by amint** [comment] 2017-07-21 07:47
thank you for the tip

**Comment by amint** [comment] 2017-07-29 22:13
Will this be fixed in this sprint?

**Comment by dacodekid** [comment] 2017-08-10 14:39
@amint this could be a duplicate of [this issue](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/issues/183).  Plz see whether my workaround helps.

**Closed** 2020-07-01 22:58 UTC
Labels: wontfix
